[PARAMETERS]
no_of_transactions = 2208       ; 24 tx/día × 92 días
lambda             = 24
no_of_agents       = 1000
alpha              = 0.5
latency            = 1           
tip_selection_algo = weighted
agent_choice       = None
printing           = False

[BEHAVIOR]
; ninguno activado en el baseline
